# Generated by Django 4.2.6 on 2023-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userNum', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
