# Generated by Django 4.2.6 on 2023-11-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userNum', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(default='99999', max_length=45, unique=True)),
                ('password', models.CharField(default='default-password', max_length=128)),
                ('name', models.CharField(default='홍길동', max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
