# Generated by Django 4.2.6 on 2023-10-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('postNum', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.TimeField()),
            ],
            options={
                'db_table': 'commmunity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeCommunity',
            fields=[
                ('like_communityNum', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like_community',
                'managed': False,
            },
        ),
    ]
