# Generated by Django 4.2.6 on 2023-10-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn13', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.TextField()),
                ('cover', models.TextField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=30)),
                ('mallType', models.CharField(max_length=10)),
                ('priceStandard', models.IntegerField()),
                ('link', models.TextField()),
                ('adult', models.CharField(max_length=10)),
                ('pubDate', models.DateField()),
                ('categoryName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('depth1', models.CharField(max_length=20)),
                ('depth2', models.CharField(max_length=20)),
                ('depth3', models.CharField(max_length=20)),
                ('depth4', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeBook',
            fields=[
                ('like_bookNum', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like_book',
                'managed': False,
            },
        ),
    ]
